# キーボードの設定をカスタマイズする
# 項目は https://zmk.dev/docs/config/... を参照

# NKROを有効化する
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# 新しいZMK/Zephyr環境でNKROを安定させるための拡張レポート設定
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y

# 念のため、古い6KROのデータを完全に無効化する
CONFIG_ZMK_HID_REPORT_TYPE_6KRO=n

# スリープモードを使う
CONFIG_ZMK_SLEEP=y
# 15分放置でスリープ
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# Bluetooth接続を安定化
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# マウスポインターキーを使う（効かなそう？）
# CONFIG_ZMK_POINTING=y
